[project]
name = "txiki-gpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.4",
    "requests>=2.32.5",
    "tiktoken>=0.12.0",
    "torch>=2.9.0",
]
